version: "3.9"
services:
    db:
        image: postgres
        volumes:
            - ./tmp/db:/var/lib/postgresql/data
    web:
        build: .
        volumes:
            - .:/zukan
        ports:
            - "4567:4567"
        depends_on:
            - db