version: "3.9"
services:
    db:
        image: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
    web:
        build: .
        volumes:
            - .:/zukan
        ports:
            - "4567:4567"
        depends_on:
            db:
                condition: service_healthy
volumes:
    postgres: